### ISSUE TITLE
Updating a datepicker

### ISSUE THREAD

**Issue by sshaik305** [PrithiviRajG/Ionic-3-Native-Date-Picker-example#1]
Do anyone have idea on how to pass the date to the date picker for updating a form

I thought of passing the date along with the following code
let selectedDate = '24/11/2017';
this.datePicker.show({
		  date: selectedDate,
		  mode: 'date',
		  minDate: new Date(),
})
but it showing that selectedDate is not defined, any suggestions/fixes for this..
Thanks in advance guys

**Comment by PrithiviRajG** [comment]
Declare date like` let selectedDate = new Date("11/24/2017");` to use the date.
If you want current date use `let selectedDatedate = new Date();`

**Comment by sshaik305** [comment]
Thank you very much Prithvi...
You made my day great
